"""trading/brain/gui/reflection.py — the LEARN layer: Reflexion-style self-critique.

Adapted from vendor/reflexion (the try → fail → reflect → store-lesson loop). After each
attempted GUI task the agent writes a short, verbal lesson from what happened and appends it
to a persisted failure/lesson database. Before the next attempt at a similar task it recalls
the relevant lessons so it does not repeat the same mistake — exactly the Reflexion mechanism,
CPU-only and LLM-free (the lesson text is generated by a deterministic rule synthesizer; when
an LLM is configured the agent can swap in a richer reflection, but it is never required).
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field

STATE_FILE = "gui_reflections.json"


def _tokens(text: str) -> set[str]:
    return {w for w in "".join(c.lower() if c.isalnum() else " " for c in text).split()
            if len(w) > 2}


@dataclass
class Lesson:
    """One verbal lesson distilled from an attempted task."""
    task: str
    outcome: str                 # "success" | "failure"
    lesson: str
    detail: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Lesson":
        keep = {k: d[k] for k in d if k in cls.__dataclass_fields__}
        return cls(**keep)


class GuiReflector:
    """Reflexion loop: reflect(task, trajectory, outcome) → lesson; recall(task) → lessons."""

    def __init__(self, *, persist: bool = True):
        self.persist = persist
        self.lessons: list[Lesson] = []
        self._load()

    def _load(self) -> None:
        if not self.persist:
            return
        from trading import state
        blob = state.load_json(STATE_FILE, {})
        self.lessons = [Lesson.from_dict(d) for d in blob.get("lessons", [])]

    def _save(self) -> None:
        if not self.persist:
            return
        from trading import state
        state.save_json(STATE_FILE, {"lessons": [l.to_dict() for l in self.lessons]})

    # ---- reflect ----------------------------------------------------------
    def reflect(self, task: str, trajectory: list[dict], ok: bool) -> Lesson:
        """Distil a verbal lesson from one attempt and store it (the Reflexion step)."""
        outcome = "success" if ok else "failure"
        lesson = self._synthesize(task, trajectory, ok)
        l = Lesson(task=task, outcome=outcome, lesson=lesson,
                   detail={"steps": len(trajectory)})
        self.lessons.append(l)
        self._save()
        return l

    @staticmethod
    def _synthesize(task: str, trajectory: list[dict], ok: bool) -> str:
        """Rule-based verbal reflection (LLM-free). Names the failing step + a corrective hint."""
        if ok:
            return f"task '{task}' succeeded; the action sequence is reliable — promote to a skill."
        # find the first failed/refused step and explain it
        for st in trajectory:
            if not st.get("ok", True):
                reason = st.get("reason") or st.get("detail", {})
                act = st.get("action", "?")
                if "armed" in str(reason) or "allow_live" in str(reason):
                    return (f"task '{task}' failed at '{act}': real-money guard refused it. "
                            f"Lesson: arm the executor (allow_live) + confirm, or keep it paper.")
                if "playwright" in str(reason):
                    return (f"task '{task}' needs DOM clicking but playwright is not installed. "
                            f"Lesson: use the in-process/http control path, or install playwright.")
                if "URLError" in str(reason) or "unreachable" in str(reason).lower():
                    return (f"task '{task}' failed at '{act}': target unreachable. "
                            f"Lesson: verify the dashboard/Freqtrade is up before acting.")
                return f"task '{task}' failed at '{act}': {reason}. Lesson: re-plan this step."
        return f"task '{task}' did not complete; no single step flagged — re-observe then retry."

    # ---- recall -----------------------------------------------------------
    def recall(self, task: str, k: int = 3) -> list[Lesson]:
        """Recall the most relevant prior lessons for a task (keyword overlap)."""
        want = _tokens(task)
        scored = []
        for l in self.lessons:
            overlap = len(want & _tokens(l.task))
            if overlap:
                scored.append((overlap, l))
        scored.sort(key=lambda t: t[0], reverse=True)
        return [l for _, l in scored[:k]]

    def failures(self) -> list[Lesson]:
        return [l for l in self.lessons if l.outcome == "failure"]

    def to_json(self) -> dict:
        return {"n_lessons": len(self.lessons),
                "n_failures": len(self.failures()),
                "recent": [l.to_dict() for l in self.lessons[-10:]]}
