"""trading/crypto/freqtrade/launch.py — generate the config and print the launch command.

This does NOT spawn Freqtrade (same contract as the OpenAlgo server: the engine is a separate
process the operator runs). It writes a config.json derived from our crypto_config / TRADING_MODE
and prints the exact `freqtrade trade ...` command, so paper(dry-run)/live always match the system.

    .venv/bin/python -m trading.crypto.freqtrade.launch
"""
from __future__ import annotations

import os
import sys

from trading.crypto.config import crypto_config
from trading.crypto.freqtrade.config_template import HERE, STRATEGY, write_config

# project root = three levels up from this file (trading/crypto/freqtrade/launch.py)
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
START_SH = os.path.join(HERE, "start.sh")


def _write_start_script(cfg_path: str, user_dir: str) -> str:
    """Write an executable wrapper so the long command can't break on a terminal line-wrap."""
    ft = os.path.join(ROOT, ".venv", "bin", "freqtrade")
    body = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by trading.crypto.freqtrade.launch — starts the crypto engine.\n"
        "# Regenerate with: .venv/bin/python -m trading.crypto.freqtrade.launch\n"
        "set -e\n"
        f'exec "{ft}" trade \\\n'
        f'  --config "{cfg_path}" \\\n'
        f'  --strategy {STRATEGY} \\\n'
        f'  --userdir "{user_dir}"\n'
    )
    with open(START_SH, "w") as fh:
        fh.write(body)
    os.chmod(START_SH, 0o755)
    return START_SH


def main() -> None:
    # Regenerate from the LIVE config.json overlay (control._cfg), NOT the stale/default env —
    # otherwise a manual relaunch would silently reset operator-set fields (leverage, paper
    # balance, spot/futures, paper/live) back to their startup defaults.
    from trading.crypto.freqtrade import control as _ctl
    cfg_path = write_config(cfg=_ctl._cfg())
    user_dir = os.path.join(HERE, "user_data")
    start_sh = _write_start_script(cfg_path, user_dir)
    mode = "live (REAL MONEY)" if crypto_config.is_live else "paper (dry-run)"
    print(f"Freqtrade config written: {cfg_path}")
    print(f"Mode: {mode}   exchange: {crypto_config.default_exchange}   "
          f"stake: {crypto_config.quote}   REST: {crypto_config.ft_host}")
    if not crypto_config.ft_configured:
        print("WARNING: FREQTRADE_PASSWORD is empty in .env — the REST api_server needs a "
              "password. Set FREQTRADE_USERNAME/FREQTRADE_PASSWORD before CryptoEngineClient "
              "can authenticate.")
    print("\nStart the engine — run this ONE short command (keep the terminal open):")
    print(f"  bash {start_sh}")
    print("\n(or pass --run to start it right now from here)")
    print("Then the dashboard /api/trading/crypto/status shows the live Freqtrade engine state.")
    if "--run" in sys.argv:
        print("\nStarting Freqtrade now…\n")
        os.execv("/usr/bin/env", ["/usr/bin/env", "bash", start_sh])


if __name__ == "__main__":
    main()
