"""trading/strategy/freqtrade_adapter.py — translate LibraryStrategy → Freqtrade IStrategy (Phase C).

The strategy library (241 static/institutional + 311 brain-created as of 2026-07-16, see
trading/strategy/library/registry.py) models each executable strategy as a pure, vectorized signal:
``signal(compute_features_ext(ohlcv)) -> Series[+1/-1/0]`` (target position). Freqtrade is also
vectorized and signal-based (``populate_entry_trend`` / ``populate_exit_trend``), so the
translation is faithful and thin:

    +1  -> enter_long  (hold while +1)        sig<=0 -> exit_long
    -1  -> enter_short (futures, if allowed)  sig>=0 -> exit_short

This module is imported BY the Freqtrade process (where ``freqtrade`` is importable). It guards
the freqtrade import so the rest of our repo/tests can import the helpers (registry filtering,
file generation) without freqtrade installed.

Scope: only CRYPTO-applicable, signal-based strategies are translated — crypto trades on
Freqtrade. NSE strategies run through OpenAlgo (a different path). ``data_backed`` strategies
(signal is None — they download their own data) are NOT translated here and are reported by
``skipped_strategies()`` so nothing is silently dropped (never-skip rule).
"""
from __future__ import annotations

import os
import re

# project root = two levels up from this file (trading/strategy/freqtrade_adapter.py)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# crypto segments that map onto Freqtrade
_CRYPTO_SEGMENTS = ("crypto_spot", "crypto_futures")

# Spot bots are long-only (Freqtrade rejects can_short in spot); futures bots allow shorting.
# Driven by CRYPTO_TRADING_MODE (.env) — regenerate strategy files after changing it.
def _spot_mode() -> bool:
    try:
        from trading.crypto.config import crypto_config
        return not crypto_config.is_futures
    except Exception:
        return True


SPOT_MODE = _spot_mode()


def _is_crypto(strat) -> bool:
    return any(seg in strat.segments for seg in _CRYPTO_SEGMENTS)


def crypto_strategies() -> list:
    """Executable, signal-based, crypto-applicable LibraryStrategies (the translatable set)."""
    from trading.strategy.library.registry import get_registry
    return [s for s in get_registry().executable()
            if s.signal is not None and _is_crypto(s)]


def skipped_strategies() -> list[dict]:
    """Crypto strategies we do NOT translate to Freqtrade, with the honest reason."""
    from trading.strategy.library.registry import get_registry
    out = []
    for s in get_registry().strategies:
        if not _is_crypto(s):
            continue
        if s.signal is None and getattr(s, "data_backed", False):
            out.append({"name": s.name, "reason": "data_backed (downloads own data; not a "
                                                  "bar-signal) — runs via its own backtest path"})
        elif not s.is_executable:
            out.append({"name": s.name, "reason": f"data_gated ({s.gating_reqs})"})
    return out


def class_name_for(name: str) -> str:
    """A valid, unique Python class identifier for a strategy name (the --strategy arg)."""
    ident = re.sub(r"[^0-9a-zA-Z]+", " ", name).title().replace(" ", "")
    if not ident or ident[0].isdigit():
        ident = "Lib" + ident
    return ident


def can_short_for(strat) -> bool:
    """Futures strategies may short; spot cannot (no native short on Binance spot)."""
    return ("crypto_futures" in strat.segments) and bool(strat.allow_short)


def make_freqtrade_strategy(name: str):
    """Build a Freqtrade IStrategy subclass for the named LibraryStrategy (in-process / tests).

    File generation uses a real ``class`` statement instead (see _FILE_TEMPLATE); this helper
    builds the equivalent subclass dynamically for direct use. Imported inside the Freqtrade
    process (freqtrade available there).
    """
    from trading.strategy.freqtrade_strategy_base import LibraryStrategyBase
    from trading.strategy.library.registry import get_registry

    lib = get_registry().get(name)
    if lib is None or lib.signal is None:
        raise ValueError(f"library strategy {name!r} not found / has no signal")
    cls = type(class_name_for(name), (LibraryStrategyBase,),
               {"library_name": name, "can_short": can_short_for(lib),
                "library_category": lib.category, "library_oss_source": lib.oss_source})
    return cls


# ── file generation (so Freqtrade can discover each strategy by --strategy <ClassName>) ──
# A REAL class statement → __module__ is the lib_*.py module automatically (resolver-friendly).
_FILE_TEMPLATE = '''\
"""AUTO-GENERATED by trading.strategy.freqtrade_adapter — do not edit by hand.
Library strategy: {name!r}  (category: {category}; source: {oss})
Regenerate: .venv/bin/python -m trading.strategy.freqtrade_adapter <userdir/strategies>
"""
import sys
_PROOT = {proot!r}
if _PROOT not in sys.path:
    sys.path.insert(0, _PROOT)
from trading.strategy.freqtrade_strategy_base import LibraryStrategyBase


class {cls}(LibraryStrategyBase):
    library_name = {name!r}
    # spot dry-run bot => long-only (Freqtrade rejects can_short in spot). `futures_capable`
    # records that this library strategy CAN short — flip can_short=True once the bot runs
    # trading_mode=futures (see freqtrade_adapter.SPOT_MODE).
    can_short = {can_short}
    futures_capable = {futures_capable}
    library_category = {category!r}
    library_oss_source = {oss!r}
'''


def generate_strategy_files(out_dir: str, *, spot_mode: bool | None = None) -> dict:
    """Write one Freqtrade strategy .py per translatable crypto strategy. Returns a summary.
    `spot_mode` overrides the global (controller passes the target segment's value on switch)."""
    spot = SPOT_MODE if spot_mode is None else spot_mode
    os.makedirs(out_dir, exist_ok=True)
    written, names = [], []
    for s in crypto_strategies():
        cls = class_name_for(s.name)
        fname = f"lib_{cls}.py"
        futures_capable = can_short_for(s)
        can_short = futures_capable and not spot
        with open(os.path.join(out_dir, fname), "w") as fh:
            fh.write(_FILE_TEMPLATE.format(name=s.name, category=s.category,
                                           oss=s.oss_source or "n/a", proot=PROJECT_ROOT, cls=cls,
                                           can_short=can_short, futures_capable=futures_capable))
        written.append(fname)
        names.append({"library": s.name, "class": cls, "segments": list(s.segments)})
    return {"out_dir": out_dir, "n_written": len(written),
            "strategies": names, "skipped": skipped_strategies()}


def main(argv: list[str]) -> int:
    import json
    out_dir = argv[1] if len(argv) > 1 else os.path.join(
        PROJECT_ROOT, "trading", "crypto", "freqtrade", "user_data", "strategies")
    summary = generate_strategy_files(out_dir)
    print(json.dumps({"out_dir": summary["out_dir"], "n_written": summary["n_written"],
                      "n_skipped": len(summary["skipped"])}, indent=2))
    print("classes:", ", ".join(s["class"] for s in summary["strategies"][:12])
          + (" …" if summary["n_written"] > 12 else ""))
    if summary["skipped"]:
        print(f"skipped (not Freqtrade-translatable): {len(summary['skipped'])} "
              "— see data-backed/gated path")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main(sys.argv))
